In [1]:
import pandas as pd

In [2]:
excel = pd.ExcelFile("Records Matching Task.xlsx")

print(excel.sheet_names)

['data1', 'data2']

In [5]:
data1 = pd.read_excel("Records Matching Task.xlsx", sheet_name="data1")
data2 = pd.read_excel("Records Matching Task.xlsx", sheet_name="data2")

In [6]:
print("Data1 Shape:", data1.shape)
print("Data2 Shape:", data2.shape)

data1.head()

Data1 Shape: (9477, 3)
Data2 Shape: (9479, 3)

         Order ID       Product ID  Qty
0  CA-2014-100090  FUR-TA-10003715    3
1  CA-2014-100090  OFF-BI-10001597    6
2  CA-2014-100293  OFF-PA-10000176    6
3  CA-2014-100328  OFF-BI-10000343    1
4  CA-2014-100363  OFF-FA-10000611    2

In [7]:
data2.head()

         Order ID       Product ID  Qty
0  CA-2014-100090  FUR-TA-10003715    3
1  CA-2014-100090  OFF-BI-10001597    6
2  CA-2014-100293  OFF-PA-10000176    6
3  CA-2014-100328  OFF-BI-10000343    1
4  CA-2014-100363  OFF-FA-10000611    2

In [8]:
data1["Key"] = (
    data1["Order ID"].astype(str)
    + "_"
    + data1["Product ID"].astype(str)
)

data2["Key"] = (
    data2["Order ID"].astype(str)
    + "_"
    + data2["Product ID"].astype(str)
)

In [9]:
missing_in_data2 = data1[~data1["Key"].isin(data2["Key"])]

print("Records present in Data1 but missing in Data2:")
print(missing_in_data2.shape[0])

Records present in Data1 but missing in Data2:
506

In [10]:
missing_in_data1 = data2[~data2["Key"].isin(data1["Key"])]

print("Records present in Data2 but missing in Data1:")
print(missing_in_data1.shape[0])

Records present in Data2 but missing in Data1:
508

In [11]:
missing_in_data1["Qty"].sum()

np.int64(1956)

In [12]:
print("Sum of Qty:", missing_in_data1["Qty"].sum())

Sum of Qty: 1956

In [13]:
combined = pd.concat([data1["Key"], data2["Key"]])

combined.nunique()

9985

In [14]:
with pd.ExcelWriter("Output.xlsx") as writer:
    missing_in_data2.to_excel(writer, sheet_name="Missing_in_Data2", index=False)
    missing_in_data1.to_excel(writer, sheet_name="Missing_in_Data1", index=False)

In [15]:
files.download("Output.xlsx")

NameError: name 'files' is not defined